name: Deploy

on: [push]

jobs:
  build-launcher:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ujson graphviz ply pytest atomicwrites more-itertools pluggy py attrs setuptools six django==2.1 psycopg2
    - name: Deployment of CV
      run: |
        DEPLOY_DIR=build make install -j$(nproc)
        DEPLOY_DIR=build make install-cif-compiled -j$(nproc)
        cp -r docs/examples/sources/ build/
        cd build && ./scripts/launch.py -c configs/it.json
  build-visualizer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ujson graphviz ply pytest atomicwrites more-itertools pluggy py attrs setuptools six django==2.1 psycopg2
    - name: Deployment of CV
      run: |
        DEPLOY_DIR=build make install-benchmark-visualizer -j$(nproc)
  build-frama-c-cil:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Deployment of CV
      run: |
        DEPLOY_DIR=build make install-frama-c-cil -j$(nproc)
